branches: master

pipeline:  
  # publish to public registry
  hubpublish:
    image: plugins/docker
    repo: servercentral/praeco
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  # publish to internal registry
  tagandpublish:
    image: registry.servercentral.com/drone-plugins/tagandpublish
    pull: true
    environment:
      - PROJECT_NAME=servercentral/praeco
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deployment:
    image: registry.servercentral.com/drone-plugins/awxdeployment
    pull: true
    environment:
      - PROJECT_PLAYBOOK=playbooks/public-docker-cluster/praeco.yml
    volumes:
      - /etc/tower/tower_cli.cfg:/etc/tower/tower_cli.cfg
    when:
      event: push
      branch: master 
      status: success
